package hooks

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const (
	markerStart = "# >>> wt-helper start"
	markerEnd   = "# <<< wt-helper end"
)

func hookBlock(mainRepo string) string {
	return markerStart + `
# Auto-generated by wt-helper — do not edit between markers
OLD_REF=$1
NULL_SHA="0000000000000000000000000000000000000000"
CONF="` + mainRepo + `/.git/worktree-helper.conf"

if [ "$OLD_REF" = "$NULL_SHA" ] && [ -f "$CONF" ]; then
    ENVRC_SRC=$(grep '^envrc-source' "$CONF" | sed 's/^envrc-source *= *//')
    IS_TEMPLATE=$(grep '^is-template' "$CONF" | sed 's/^is-template *= *//')
    if [ -n "$ENVRC_SRC" ] && [ -f "$ENVRC_SRC" ]; then
        __wt_install_envrc() {
            if [ "$IS_TEMPLATE" = "true" ]; then
                VARS_FILE=$(grep '^vars-file' "$CONF" | sed 's/^vars-file *= *//')
                if [ -n "$WT_VARS_FILE" ] && [ -f "$WT_VARS_FILE" ]; then
                    VARS_FILE="$WT_VARS_FILE"
                fi
                HELPER_BIN=$(grep '^helper-bin' "$CONF" | sed 's/^helper-bin *= *//')
                if [ -z "$HELPER_BIN" ] || [ ! -x "$HELPER_BIN" ]; then
                    echo "wt-helper: helper binary not found at $HELPER_BIN" >&2
                    return 1
                fi
                BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "detached")
                VARS_FLAG=""
                if [ -n "$VARS_FILE" ] && [ -f "$VARS_FILE" ]; then
                    VARS_FLAG="--vars $VARS_FILE"
                fi
                "$HELPER_BIN" render-template "$ENVRC_SRC" \
                    $VARS_FLAG \
                    --worktree-path "$PWD" \
                    --branch "$BRANCH" \
                    > ./.envrc
            else
                cp "$ENVRC_SRC" ./.envrc
            fi
        }
        if [ -f .envrc ]; then
            printf "wt-helper: worktree already has .envrc — overwrite? [y/N] "
            read answer
            case "$answer" in
                y|Y) __wt_install_envrc ;;
                *) echo "wt-helper: skipped .envrc copy"; exit 0 ;;
            esac
        else
            __wt_install_envrc
        fi
        if command -v direnv >/dev/null 2>&1; then
            direnv allow .
        fi
        echo "wt-helper: .envrc installed and allowed"
    fi
    DEP_DIRS=$(grep '^dep-dirs' "$CONF" | sed 's/^dep-dirs *= *//')
    DEP_MODE=$(grep '^dep-mode' "$CONF" | sed 's/^dep-mode *= *//')
    if [ -n "$DEP_DIRS" ]; then
        MAIN_REPO=$(grep '^main-repo' "$CONF" | sed 's/^main-repo *= *//')
        for dir in $(echo "$DEP_DIRS" | tr ',' ' '); do
            if [ "$DEP_MODE" = "copy" ]; then
                rm -rf "$PWD/$dir" && cp -r "$MAIN_REPO/$dir" "$PWD/$dir"
            else
                ln -sf "$MAIN_REPO/$dir" "$PWD/$dir"
            fi
        done
        echo "wt-helper: linked dep dirs: $DEP_DIRS"
    fi
fi
` + markerEnd
}

// InstallPostCheckout writes or updates the post-checkout hook in gitDir/hooks/.
func InstallPostCheckout(gitDir, mainRepo string, force bool) error {
	hookPath := filepath.Join(gitDir, "hooks", "post-checkout")

	var existing string
	if data, err := os.ReadFile(hookPath); err == nil {
		existing = string(data)
	}

	// Check if we already have our markers
	if strings.Contains(existing, markerStart) && strings.Contains(existing, markerEnd) {
		// Replace existing block
		before := existing[:strings.Index(existing, markerStart)]
		after := existing[strings.Index(existing, markerEnd)+len(markerEnd):]
		content := before + hookBlock(mainRepo) + after
		return writeHook(hookPath, content)
	}

	// Hook exists without our markers
	if existing != "" {
		if !force {
			fmt.Printf("wt-helper: %s already exists (not generated by wt-helper).\n", hookPath)
			fmt.Print("Append wt-helper hook section? [y/N] ")
			var answer string
			fmt.Scanln(&answer)
			if answer != "y" && answer != "Y" {
				fmt.Println("wt-helper: skipping post-checkout hook")
				return nil
			}
		}
		// Append our block
		content := strings.TrimRight(existing, "\n") + "\n\n" + hookBlock(mainRepo) + "\n"
		return writeHook(hookPath, content)
	}

	// No hook exists — create fresh
	content := "#!/bin/sh\n\n" + hookBlock(mainRepo) + "\n"
	return writeHook(hookPath, content)
}

func writeHook(path, content string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("mkdir hooks: %w", err)
	}
	if err := os.WriteFile(path, []byte(content), 0o755); err != nil {
		return fmt.Errorf("write hook: %w", err)
	}
	fmt.Printf("wt-helper: wrote %s\n", path)
	return nil
}

// InstallWtRemoveAlias registers the git alias for worktree deletion.
func InstallWtRemoveAlias(repoRoot string) error {
	alias := `!__wt_remove() {
    WT_PATH="$1"; shift
    if [ -z "$WT_PATH" ]; then
        echo "usage: git wt-remove <worktree-path> [--force]"
        return 1
    fi
    CONF="$(git rev-parse --git-dir)/worktree-helper.conf"
    if [ -f "$CONF" ]; then
        WRAPUP=$(grep '^wrapup-cmd' "$CONF" | sed 's/^wrapup-cmd *= *//')
        if [ -n "$WRAPUP" ]; then
            echo "wt-helper: running wrapup for $WT_PATH..."
            if ! bash -c '
                for f in "$HOME/.profile" "$HOME/.bashrc"; do
                    [ -f "$f" ] && . "$f" 2>/dev/null && break
                done
                cd "$2" 2>/dev/null
                [ -f .envrc ] && . .envrc 2>/dev/null
                eval "$1" "$2"
            ' _ "$WRAPUP" "$WT_PATH"; then
                echo "wt-helper: wrapup failed: $WRAPUP" >&2
                return 1
            fi
        fi
    fi
    if git worktree remove "$WT_PATH" "$@"; then
        echo "wt-helper: worktree $WT_PATH removed"
    else
        echo "wt-helper: git worktree remove failed (use --force if worktree has modifications)" >&2
        return 1
    fi
}; __wt_remove`

	cmd := exec.Command("git", "config", "alias.wt-remove", alias)
	cmd.Dir = repoRoot
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("git config alias.wt-remove: %w", err)
	}
	fmt.Println("wt-helper: installed git alias 'wt-remove'")
	return nil
}

// InstallWtAddAlias registers the git alias for worktree creation with interactive prompting.
func InstallWtAddAlias(repoRoot string) error {
	alias := `!__wt_add() {
    CONF="$(git rev-parse --git-dir)/worktree-helper.conf"
    if [ ! -f "$CONF" ]; then
        echo "wt-helper: not configured. Run 'wt-helper setup' first." >&2
        return 1
    fi
    IS_TEMPLATE=$(grep '^is-template' "$CONF" | sed 's/^is-template *= *//')
    if [ "$IS_TEMPLATE" = "true" ]; then
        ENVRC_SRC=$(grep '^envrc-source' "$CONF" | sed 's/^envrc-source *= *//')
        VARS_FILE=$(grep '^vars-file' "$CONF" | sed 's/^vars-file *= *//')
        HELPER_BIN=$(grep '^helper-bin' "$CONF" | sed 's/^helper-bin *= *//')
        if [ -z "$HELPER_BIN" ] || [ ! -x "$HELPER_BIN" ]; then
            echo "wt-helper: helper binary not found at $HELPER_BIN" >&2
            return 1
        fi
        TMP_VARS=$(mktemp /tmp/wt-vars-XXXXX.json)
        VARS_FLAG=""
        if [ -n "$VARS_FILE" ] && [ -f "$VARS_FILE" ]; then
            VARS_FLAG="--vars $VARS_FILE"
        fi
        "$HELPER_BIN" prepare-vars "$ENVRC_SRC" \
            $VARS_FLAG \
            --output "$TMP_VARS"
        export WT_VARS_FILE="$TMP_VARS"
        git worktree add "$@"
        RET=$?
        rm -f "$TMP_VARS"
        return $RET
    fi
    git worktree add "$@"
}; __wt_add`

	cmd := exec.Command("git", "config", "alias.wt-add", alias)
	cmd.Dir = repoRoot
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("git config alias.wt-add: %w", err)
	}
	fmt.Println("wt-helper: installed git alias 'wt-add'")
	return nil
}
