package config

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type Config struct {
	MainRepo    string
	EnvrcSource string
	WrapupCmd   string
	VarsFile    string
	HelperBin   string
	IsTemplate  bool
	DepDirs     string
	DepMode     string
}

func confPath(repoRoot string) string {
	return filepath.Join(repoRoot, ".git", "worktree-helper.conf")
}

func Exists(repoRoot string) bool {
	_, err := os.Stat(confPath(repoRoot))
	return err == nil
}

func Load(repoRoot string) (*Config, error) {
	f, err := os.Open(confPath(repoRoot))
	if err != nil {
		return nil, fmt.Errorf("open config: %w", err)
	}
	defer f.Close()

	cfg := &Config{}
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			continue
		}
		key := strings.TrimSpace(parts[0])
		val := strings.TrimSpace(parts[1])
		switch key {
		case "main-repo":
			cfg.MainRepo = val
		case "envrc-source":
			cfg.EnvrcSource = val
		case "wrapup-cmd":
			cfg.WrapupCmd = val
		case "vars-file":
			cfg.VarsFile = val
		case "helper-bin":
			cfg.HelperBin = val
		case "is-template":
			cfg.IsTemplate = val == "true"
		case "dep-dirs":
			cfg.DepDirs = val
		case "dep-mode":
			cfg.DepMode = val
		}
	}
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("read config: %w", err)
	}
	return cfg, nil
}

func Save(repoRoot string, cfg *Config) error {
	path := confPath(repoRoot)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("mkdir: %w", err)
	}
	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("create config: %w", err)
	}
	defer f.Close()

	fmt.Fprintln(f, "# Generated by wt-helper — do not edit manually")
	fmt.Fprintf(f, "main-repo = %s\n", cfg.MainRepo)
	if cfg.EnvrcSource != "" {
		fmt.Fprintf(f, "envrc-source = %s\n", cfg.EnvrcSource)
	}
	if cfg.WrapupCmd != "" {
		fmt.Fprintf(f, "wrapup-cmd = %s\n", cfg.WrapupCmd)
	}
	if cfg.VarsFile != "" {
		fmt.Fprintf(f, "vars-file = %s\n", cfg.VarsFile)
	}
	if cfg.HelperBin != "" {
		fmt.Fprintf(f, "helper-bin = %s\n", cfg.HelperBin)
	}
	fmt.Fprintf(f, "is-template = %v\n", cfg.IsTemplate)
	if cfg.DepDirs != "" {
		fmt.Fprintf(f, "dep-dirs = %s\n", cfg.DepDirs)
	}
	if cfg.DepMode != "" {
		fmt.Fprintf(f, "dep-mode = %s\n", cfg.DepMode)
	}
	return nil
}
